{%- if specific_data.base_image%}
FROM {{ specific_data.base_image }}:{{ base_distro_tag }}
{% else %}
FROM {{ base_image }}:{{ base_distro_tag }}
{% endif -%}
{%- if specific_data.maintainer %}
MAINTAINER {{ specific_data.maintainer }}
{% else %}
MAINTAINER {{ maintainer }}
{% endif -%}

ENV CONTAINER_NAME {{ image_name }}

{% if specific_data.gid %}
RUN groupadd --force --gid {{ specific_data.gid }} {{ specific_data.gname }} \
&& useradd -M --shell /usr/sbin/nologin --uid {{ specific_data.uid }} --gid {{ specific_data.gid }} {{ specific_data.gname }}
{% endif %}

COPY ./ /work-dir/

#### Customize PS1 to be used with bash shell
RUN cat /work-dir/custom_bashrc >> /etc/skel/.bashrc \
&& cat /work-dir/custom_bashrc >> /root/.bashrc \
&& yum install -y /work-dir/pkgs/sudo-1.8.19p2-14.el7_5.x86_64.rpm \
&& cp /work-dir/pkgs/dumb-init_1.2.2_amd64 /usr/local/bin/dumb-init \
&& chmod +x /usr/local/bin/dumb-init \
&& cp /work-dir/set_configs.py /usr/local/bin/set_configs
&& chmod 755 /usr/local/bin/kolla_set_configs \
&& cp /work-dir/cmd_start /usr/local/bin/cmd_start \
&& chmod 755 /usr/local/bin/cmd_start

# PS1 var when used /bin/sh shell
ENV PS1="$(tput bold)($(printenv CONTAINER_NAME))$(tput sgr0)[$(id -un)@$(hostname -s) $(pwd)]$ "

RUN rm -rf /work-dir
CMD ["cmd_start"]